version: '3'

services:
  app:
    build: .
    networks:
      - app-network
    depends_on:
      - db
    environment:
      - RAILS_ENV=development

  db:
    image: alpine:latest
    command: sh -c "apk add --no-cache sqlite && tail -f /dev/null"
    volumes:
      - sqlite_data:/var/lib/sqlite
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - app

networks:
  app-network:
    driver: bridge

volumes:
  sqlite_data: